In [20]:
import numpy as np

Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function

In [21]:
arr = np.array([1, 2, 3])
list1 = arr.tolist()
print(list1)

[1, 2, 3]


Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

In [50]:
x= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
i=0
y=[]
for i in range(-1,2):    
    y.append(x[i,i])
print(y)
print(sum(y))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[9, 1, 5]
15


In [57]:
x= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
a=sum(np.diag(x))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [59]:
x= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
b=np.trace(x)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

In [123]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[A>2])
    

[3 4 5 6 7 8 9]


In [176]:
v= np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(0,v.shape[0]):     
    for j in range(0,v.shape[1]):
        if v[i,j]>2:
            print(v[i,j])
#c t du pure hasard 


3
4
5
6
7
8
9


Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. 

In [63]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(B)
C=np.vstack((A,B))
D=np.hstack((A,B))
E=np.concatenate((A, B), axis=0)
print(C)
print(D)
print(E)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [106]:
A= np.array([[1,2,0],[4,5,6],[7,8,56]])
x = A.shape[0]
for i in range (x):
    A[i]=A[i]-np.mean(A[i])
print(A)

[[  0   1  -1]
 [ -1   0   1]
 [-16 -15  32]]


In [101]:
x

3